class Autogenerated {
String? title;
String? description;
String? image;
String? date;

Autogenerated({this.title, this.description, this.image, this.date});

Autogenerated.fromJson(Map<String, dynamic> json) {
title = json['title'];
description = json['description'];
image = json['image'];
date = json['date'];
}

Map<String, dynamic> toJson() {
  final Map<String, dynamic> data = new Map<String, dynamic>();
  data['title'] = this.title;
  data['description'] = this.description;
  data['image'] = this.image;
  data['date'] = this.date;
  return data;
}
}